// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: battle/battle.proto

/* eslint-disable */
import type { BattleFieldData, FrameData, RouteInfo } from "../common/battle_data";
import type { Reward } from "../common/item_data";


/** 发送命令 */
export interface CSendCommand {
  /** 卡牌实例id */
  instId: number;
  /** 卡牌模板id */
  card: number;
  /** 路线 */
  routes: RouteInfo[];
}

export interface SSendCommand {
}

/** 通知服务器资源加载完成 */
export interface CResLoadCommpelte {
}

export interface SResLoadComplete {
}

/** 丢弃卡片 */
export interface CRemoveCard {
  /** 卡牌实例id */
  instId: number;
}

export interface SRemoveCard {
}

/** 通知服务器战斗结束 */
export interface CBattleOver {
  /** 获胜方 */
  winner: string;
  /** 双方杯数变化 */
  cups: number[];
  /** 皇冠数 */
  crowns: number[];
  /** 反败为胜 */
  turnTheTile: number;
  /** 战斗结束帧 */
  endFrame: number;
}

export interface SBattleOver {
}

/** 战斗中抽卡 */
export interface CDrawCard {
}

export interface SDrawCard {
  instId: number;
  cardId: number;
}

/** 获取本地战斗奖励 */
export interface CGetLocalWinAwards {
}

export interface SGetLocalWinAwards {
  awards: Reward[];
}

/** 检查是否在战斗中 */
export interface CCheckIsInBattle {
}

export interface SCheckIsInBattle {
  replayData: BattleFieldData | undefined;
}

/** 请求从当前帧开始之后的最新帧数据，用于在战斗中断线重连 */
export interface CRequestFrameData {
}

export interface SRequestFrameData {
  curFrame: number;
  frameData: { [key: number]: FrameData };
}

export interface SRequestFrameData_FrameDataEntry {
  key: number;
  value: FrameData | undefined;
}

/**
 * 战斗推送消息
 * =====================
 * 通知战斗已经初始化，客户端收到此消息后开始加载资源
 */
export interface PNotifyBattleInit {
}

/** 通知战斗开始 */
export interface PNotifyBattleStart {
}

/** 同步帧数据 */
export interface PSyncFrameData {
}

/** 通知发牌 */
export interface PNotifyNewCard {
}

/** 通知能量回复 */
export interface PNotifyPowerRecover {
}

/** 通知战斗结束 */
export interface PNotifyBattleOver {
}

/** 通知敌方手牌数量 */
export interface PNotifyEnemyCardNum {
}
