// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/common.proto

/* eslint-disable */


export interface WebsocketMessage {
  /** 客户端上行传递值,由jsonmap指定 */
  uri: string;
  /**  */
  method: string;
  /**  */
  messageType: string;
  /**  */
  messagePayload: Buffer;
  /**  */
  uuid: string;
  /**  */
  errno: number;
  /**  */
  errmsg: string;
  timestamp: number;
}
