// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/enum.proto

/* eslint-disable */


/** 踢人原因 */
export enum KickPlayerReason {
  /** ClientLeave - 客户端主动离开 */
  ClientLeave = 0,
  /** DuplicateLogin - 重复登录 */
  DuplicateLogin = 1,
  /** ServerShutdown - 服务器关闭 */
  ServerShutdown = 2,
  /** GMKick - GM后台操作 */
  GMKick = 3,
  /** Banned - 封号踢人 */
  Banned = 4,
  UNRECOGNIZED = -1,
}
