// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/game.proto

/* eslint-disable */
import type { KickPlayerReason } from "../common/enum";


/** 登录协议 */
export interface CLogin {
  name: string;
  password: string;
}

export interface SLogin {
  playerId: number;
}

/** 回显协议 */
export interface CEcho {
  msg: string;
}

export interface SEcho {
  msg: string;
}

/** 踢出指定玩家 */
export interface CKickPlayers {
  playerIds: number[];
  reason: KickPlayerReason;
}

export interface SKickPlayers {
}

/** 踢出所有玩家 */
export interface CKickAllPlayers {
  reason: KickPlayerReason;
}

export interface SKickAllPlayers {
}
