// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: gate/gate.proto

/* eslint-disable */
import type { KickPlayerReason } from "../common/enum";


/** 踢出单个玩家 */
export interface CKickPlayer {
  playerId: number;
  reason: KickPlayerReason;
}

export interface SKickPlayer {
}

/** 踢出指定服务器的玩家 */
export interface CKickGamePlayers {
  serverId: number;
  reason: KickPlayerReason;
}

export interface SKickGamePlayers {
}

/** 广播消息，推送给当前gate上的所有玩家 */
export interface CBroadcastMessage {
  msgType: string;
  msgBody: Buffer;
}

export interface SBroadcastMessage {
}

/** 广播指定服务器的消息 */
export interface CBroadcastGameMessage {
  serverId: number;
  msgType: string;
  msgBody: Buffer;
}

export interface SBroadcastGameMessage {
}
