// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: guild/guild.proto

/* eslint-disable */
import type { GuildData } from "../common/guild_data";


/** 获取公会列表 */
export interface CGetGuildList {
}

export interface SGuildList {
  guilds: GuildData[];
}
