// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/battle_data.proto

/* eslint-disable */


/** 战斗状态 */
export enum BattleState {
  BATTLE_STATE_UNKNOWN = 0,
  /** BATTLE_STATE_INIT - 初始化 */
  BATTLE_STATE_INIT = 1,
  /** BATTLE_STATE_LOADING - 资源加载中 */
  BATTLE_STATE_LOADING = 2,
  /** BATTLE_STATE_COUNT_DOWN - 开战倒计时 */
  BATTLE_STATE_COUNT_DOWN = 3,
  /** BATTLE_STATE_FIGHTING - 战斗中 */
  BATTLE_STATE_FIGHTING = 4,
  /** BATTLE_STATE_OVER - 战斗结束 */
  BATTLE_STATE_OVER = 5,
  /** BATTLE_STATE_DELETE - 等待删除 */
  BATTLE_STATE_DELETE = 6,
  UNRECOGNIZED = -1,
}

/** 战场类型 */
export enum BattleFieldType {
  /** BATTLE_FIELD_INVALID - 无效类型 */
  BATTLE_FIELD_INVALID = 0,
  /** BATTLE_FIELD_NORMAL - 正常战斗 */
  BATTLE_FIELD_NORMAL = 1,
  /** BATTLE_FIELD_REPLAY - 战斗回放 */
  BATTLE_FIELD_REPLAY = 2,
  /** BATTLE_FIELD_CHECK_RESULT - 检查战斗结果 */
  BATTLE_FIELD_CHECK_RESULT = 3,
  UNRECOGNIZED = -1,
}

export enum BattleSide {
  /** LEFT - 左边 */
  LEFT = 0,
  /** RIGHT - 右边 */
  RIGHT = 1,
  MAX = 3,
  UNRECOGNIZED = -1,
}

export enum RouteType {
  /** DOWN - 下路 */
  DOWN = 0,
  /** MIDDLE - 中路 */
  MIDDLE = 1,
  /** UP - 上路 */
  UP = 2,
  UNRECOGNIZED = -1,
}

/** 英雄状态 */
export enum HeroState {
  /** HERO_STATE_INIT - 初始化状态 */
  HERO_STATE_INIT = 0,
  /** HERO_STATE_SEARCH - 搜索 */
  HERO_STATE_SEARCH = 1,
  /** HERO_STATE_MOVE - 移动 */
  HERO_STATE_MOVE = 2,
  /** HERO_STATE_ATTACK - 攻击中 */
  HERO_STATE_ATTACK = 3,
  /** HERO_STATE_DELETE - 等待删除 */
  HERO_STATE_DELETE = 4,
  /** HERO_STATE_OVER - 战斗结束 */
  HERO_STATE_OVER = 888,
  /** HERO_STATE_DEAD - 死亡 */
  HERO_STATE_DEAD = 999,
  /** HERO_STATE_ERROR - BUG了 */
  HERO_STATE_ERROR = 1888,
  UNRECOGNIZED = -1,
}

/** 子弹状态 */
export enum BulletState {
  BULLET_STATE_NORMAL = 0,
  BULLET_STATE_DEAD = 1,
  BULLET_STATE_DELETE = 2,
  UNRECOGNIZED = -1,
}

export enum TargetType {
  TARGET_TYPE_All = 0,
  TARGET_TYPE_FRIEND = 1,
  TARGET_TYPE_ENEMY = 2,
  UNRECOGNIZED = -1,
}

/** buff效果类型 */
export enum BuffEffectType {
  EFFECT_TYPE_UNKNOWN = 0,
  /** BAN_MOVE - 禁止移动 */
  BAN_MOVE = 1,
  /** BAN_ATTACK - 禁止攻击 */
  BAN_ATTACK = 2,
  /** IMMNUE_CONTROL - 免疫控制 */
  IMMNUE_CONTROL = 3,
  /** IMMNUE_DAMAGE - 免疫伤害 */
  IMMNUE_DAMAGE = 4,
  /** INVINCIBLE - 无敌 */
  INVINCIBLE = 5,
  UNRECOGNIZED = -1,
}

/** 技能寻找目标方式 */
export enum SkillFindTargetWay {
  /** SINGLE - 单体目标 */
  SINGLE = 0,
  UNRECOGNIZED = -1,
}

/**
 * 计算技能，子弹伤害所需要的属性索引
 * 伤害、治疗量、暴击几率、格挡几率、闪避几率、暴击伤害、伤害吸血。
 */
export enum DamageAttrIndex {
  Damage = 0,
  Healing = 1,
  CritPer = 2,
  BlockPer = 3,
  DodgePer = 4,
  CrtiDmgPer = 5,
  SuckBloodPer = 6,
  UNRECOGNIZED = -1,
}

/** 0:普通命中 1:闪避 2:格挡 3:暴击 999:免疫 */
export enum DamageType {
  NORMAL = 0,
  DODGE = 1,
  BLOCK = 2,
  CRIT = 3,
  IMMUNE = 999,
  UNRECOGNIZED = -1,
}

export enum CardRemoveType {
  REMOVE_TYPE_UNKNOWN = 0,
  /** REPLAY - 录像 */
  REPLAY = 1,
  /** COMMAND - 召唤移除 */
  COMMAND = 2,
  /** DROP - 丢弃 */
  DROP = 3,
  UNRECOGNIZED = -1,
}

/** 线路数据 */
export interface RouteInfo {
  route: number;
  posX: number;
  posY: number;
}

/** 出牌数据 */
export interface CommandRoute {
  /** 在哪条线 */
  route: number;
  /** 坐标位置x */
  posX: number;
  /** 坐标位置y */
  posY: number;
  /** 是否是最前端 */
  front: boolean;
}

export interface Command {
  /** 卡牌实例id */
  instId: number;
  /** 卡牌id */
  card: number;
  /** 各线路出牌数据 */
  routes: CommandRoute[];
}

/** 弃牌参数 */
export interface RemoveCardCommond {
  /** 卡牌实例id */
  instId: number;
}

export interface Equip {
  /** 装备id */
  id: number;
}

export interface Card {
  /** 卡牌id */
  id: number;
  /** 卡牌等级 */
  level: number;
  /** 装备列表 */
  equips: Equip[];
  modelId: number;
}

/** 手牌 */
export interface HandCardInst {
  /** 实例id */
  id: number;
  /** 模板id */
  cardId: number;
}

export interface BattlePlayerData {
  /** 玩家id */
  uid: string;
  /** 昵称 */
  nick: string;
  /** 头像 */
  avatar: number;
  /** 等级 */
  level: number;
  /** 国家 */
  country: string;
  /** 杯数 */
  cup: number;
  /** 公会名字 */
  guildName: string;
  /** 公会旗帜 */
  guildFlag: number;
  /** 玩家拥有的卡牌信息 */
  cards: Card[];
  /** 初始手牌 */
  initCards: HandCardInst[];
  /** 初始能量 */
  initEnergy: number;
  /** 下次获取卡牌的帧数 */
  nextFrame: number;
  /** 下次获取卡牌的张数 */
  cardNum: number;
  /** 发牌次数 */
  dealTimes: number;
}

/** 战斗结果集 */
export interface BattleResult {
  /** 获胜方 */
  winner: string;
  /** 双方杯数变化 */
  cups: number[];
  /** 皇冠数 */
  crowns: number[];
  /** 反败为胜 */
  turnTheTile: number;
  /** 战斗结束帧 */
  endFrame: number;
}

/** 卡牌实例信息 */
export interface CardInstData {
  /** 卡牌等级 */
  level: number;
  /** 模型id */
  modelId: number;
}

/** 帧数据，轮数据 */
export interface ClientCommand {
  /** 玩家id */
  uid: string;
  /** 在第几帧出的牌 */
  frame: number;
  /** 卡牌实例id */
  instId: number;
  /** 卡牌id */
  card: number;
  /** 各线路出牌数据 */
  routes: CommandRoute[];
}

/** 帧数据 */
export interface FrameData {
  /** 第几帧 */
  frame: number;
  /** 输入列表 */
  commands: ClientCommand[];
  /** 增加的能量点 */
  addPower: ReplayPower[];
  /** 增加的手牌 */
  addCards: ReplayHandCard[];
}

export interface BattleFieldData {
  /** 当前帧 */
  curFrame: number;
  /** 随机种子 */
  seed: number;
  /** 玩家数据 */
  playerData: BattlePlayerData[];
  /** 帧数据 */
  frameData: { [key: number]: FrameData };
  /** 战斗配置id */
  battleConfigId: number;
}

export interface BattleFieldData_FrameDataEntry {
  key: number;
  value: FrameData | undefined;
}

export interface ReplayHandCard {
  uid: string;
  card:
    | HandCardInst
    | undefined;
  /** 下一次发牌帧 */
  nextFrame: number;
  /** 下一次发牌数量 */
  cardNum: number;
}

export interface ReplayPower {
  uid: string;
  power: number;
  nextFrame: number;
}

/** 录像数据 */
export interface ReplayData {
  /** 录像索引 */
  key: string;
  /** 随机种子 */
  seed: number;
  /** 战斗时间 */
  time: number;
  /** 玩家数据 */
  playerData: BattlePlayerData[];
  /** 帧数据 */
  frameList: { [key: number]: FrameData };
  /** 战斗结果 */
  result:
    | BattleResult
    | undefined;
  /** 版本号 */
  version: string;
}

export interface ReplayData_FrameListEntry {
  key: number;
  value: FrameData | undefined;
}

/** 战报玩家概要信息 */
export interface ReplayCard {
  /** 卡牌id */
  id: number;
  /** 卡牌等级 */
  level: number;
}

export interface ReplayPlayerSummary {
  /** 玩家id */
  uid: string;
  /** 昵称 */
  nick: string;
  /** 头像 */
  avatar: string;
  /** 等级 */
  level: number;
  /** 国家 */
  country: string;
  /** 杯数 */
  cup: number;
  /** 公会名字 */
  guildName: string;
  /** 公会旗帜 */
  guildFlag: number;
  /** 玩家拥有的卡牌信息 */
  cards: ReplayCard[];
}

/** 战报概要信息 */
export interface ReplaySummaryData {
  /** 战报索引 */
  key: string;
  /** 战斗时间 */
  time: number;
  /** 战斗结果 */
  result:
    | BattleResult
    | undefined;
  /** 玩家数据 */
  playerData: ReplayPlayerSummary[];
  /** 版本号 */
  version: string;
  /** 是否能播放 */
  play: boolean;
}

export interface DamageLabelData {
  /** 1普通伤害，2暴击伤害，3普通加血，4暴击加血 */
  flag: number;
  /** 具体数值 */
  val: number;
  posX: number;
  /** 飘出位置 */
  posY: number;
}
