// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/chat_data.proto

/* eslint-disable */


/** 聊天频道的类型 */
export enum ChannelType {
  /** CHANNEL_INVALID - 无效 */
  CHANNEL_INVALID = 0,
  /** CHANNEL_PRIVATE - 私聊 */
  CHANNEL_PRIVATE = 1,
  /** CHANNEL_GUILD - 公会 */
  CHANNEL_GUILD = 2,
  /** CHANNEL_TEAM - 队伍 */
  CHANNEL_TEAM = 3,
  /** CHANNEL_WORLD - 世界 */
  CHANNEL_WORLD = 4,
  UNRECOGNIZED = -1,
}

/** 聊天内容类型 */
export enum ContentType {
  /** CONTENT_INVALID - 无效类型 */
  CONTENT_INVALID = 0,
  /** CONTENT_TEXT - 纯文本 */
  CONTENT_TEXT = 1,
  /** CONTENT_IMAGE - 图片 */
  CONTENT_IMAGE = 2,
  /** CONTENT_CARD - 卡片 */
  CONTENT_CARD = 3,
  /** CONTENT_AUDIO - 音频 */
  CONTENT_AUDIO = 4,
  /** CONTENT_VEDIO - 视频 */
  CONTENT_VEDIO = 5,
  /** CONTENT_EMOJI - 表情 */
  CONTENT_EMOJI = 6,
  UNRECOGNIZED = -1,
}

/** 聊天消息加载类型 */
export enum MessageLoadType {
  /** BACKWORD - 加载历史消息 */
  BACKWORD = 0,
  /** FORWORD - 加载最新消息 */
  FORWORD = 1,
  UNRECOGNIZED = -1,
}

/** 聊天消息类型 */
export enum ChatType {
  /** CHAT_TYPE_UNKONOWN - 未知类型 */
  CHAT_TYPE_UNKONOWN = 0,
  /** CHAT_TYPE_USER_MESSAGE - 用户消息 */
  CHAT_TYPE_USER_MESSAGE = 1,
  /** CHAT_TYPE_SYSTEM_MESSAGE - 系统消息，如时间提示 */
  CHAT_TYPE_SYSTEM_MESSAGE = 2,
  /** CHAT_TYPE_GUILD_NOTICE - 公会提示消息 */
  CHAT_TYPE_GUILD_NOTICE = 3,
  UNRECOGNIZED = -1,
}

/** 聊天频道类型 */
export enum ChatChannelType {
  CHAT_CHANNEL_TYPE_UNKNOWN = 0,
  /** CHAT_CHANNEL_TYPE_WORLD - 世界聊天 */
  CHAT_CHANNEL_TYPE_WORLD = 1,
  /** CHAT_CHANNEL_TYPE_PRIVATE - 私聊 */
  CHAT_CHANNEL_TYPE_PRIVATE = 2,
  /** CHAT_CHANNEL_TYPE_GUILD - 公会聊天 */
  CHAT_CHANNEL_TYPE_GUILD = 3,
  UNRECOGNIZED = -1,
}

/** 聊天item类型，展示ui用 */
export enum ChatItemType {
  CHAT_ITEM_TYPE_UNKNOWN = 0,
  /** CHAT_ITEM_TYPE_NORMAL - 普通状态 */
  CHAT_ITEM_TYPE_NORMAL = 1,
  /** CHAT_ITEM_TYPE_NOTICE - 提示状态 */
  CHAT_ITEM_TYPE_NOTICE = 2,
  /** CHAT_ITEM_TYPE_GUILD_NOTICE - 公会提示 */
  CHAT_ITEM_TYPE_GUILD_NOTICE = 3,
  UNRECOGNIZED = -1,
}

export interface GetChatTipsParam {
  /** 频道id */
  channelId: string;
  /** 已读消息的最大id */
  maxReadedMessageId: number;
}

export interface ChatTipsInfo {
  /** 频道id */
  channelId: string;
  /** 新消息条数 */
  newMessageCount: number;
}

/** 发送者信息 */
export interface ChatSenderInfo {
  /** 玩家uid */
  uid: string;
  /** 玩家名字 */
  name: string;
  /** 玩家头像 */
  avatar: string;
  /** 扩展信息 */
  extra: string;
}

/** 聊天内容 */
export interface ChatContentInfo {
  /** 消息类型 */
  type: ContentType;
  /** 消息本身,当 ContentType 为 TEXT: 文本字符串， PICTURE/AUDIO/VIDIO: 媒体文件url，CARD/CUSTOM: 序列化json字符串 */
  content: string;
}

/** 一条聊天消息内容 */
export interface ChatMessageInfo {
  /** 消息id */
  messageId: number;
  /** 发送者信息 */
  sender:
    | ChatSenderInfo
    | undefined;
  /** 消息内容 */
  content:
    | ChatContentInfo
    | undefined;
  /** 时间戳 */
  timestamp: number;
  /** 聊天类型 */
  chatType: ChatType;
  /** 所在频道id */
  channelId: string;
}
