// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/friend_data.proto

/* eslint-disable */


export interface FriendGuildInfo {
  /** 公会id */
  gid: string;
  /** 公会名称 */
  name: string;
  /** 公会旗帜 */
  flag: number;
  /** 成员类型 */
  type: string;
}

export interface FriendUserInfo {
  /** 玩家id */
  uid: string;
  /** 名称 */
  name: string;
  /** 头像 */
  avatar: string;
  /** 国家 */
  country: string;
  /** 等级 */
  level: number;
  /** 在线状态 */
  online: number;
  /** 公会数据 */
  guild:
    | FriendGuildInfo
    | undefined;
  /** 扩展数据 */
  extra: string;
}

export interface ApplyInfo {
  uid: string;
  name: string;
  avatar: string;
  country: string;
  level: number;
  guild: FriendGuildInfo | undefined;
  extra: string;
}
