// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/item_data.proto

/* eslint-disable */


/** 奖励数据 */
export interface Reward {
  /** 奖励类型 */
  type: string;
  /** 奖励id */
  id: string;
  /** 奖励数量 */
  count: number;
  /** 是否可交易 */
  tradable: boolean;
  /** 是否时宝箱 */
  isBoxAward: boolean;
  /** 宝箱id */
  boxId: number;
}
