// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/mail_data.proto

/* eslint-disable */


export enum MailStatus {
  MAIL_STATUS_INVALID = 0,
  /** MAIL_STATUS_NEW - 新邮件 */
  MAIL_STATUS_NEW = 1,
  /** MAIL_STATUS_READED - 已读 */
  MAIL_STATUS_READED = 2,
  /** MAIL_STATUS_CLAIMED - 已领取 */
  MAIL_STATUS_CLAIMED = 3,
  /** MAIL_STATUS_DELETED - 已删除 */
  MAIL_STATUS_DELETED = 4,
  UNRECOGNIZED = -1,
}

export enum MailType {
  MAIL_TYPE_INVALID = 0,
  /** MAIL_TYPE_SYSTEM - 系统邮件 */
  MAIL_TYPE_SYSTEM = 1,
  /** MAIL_TYPE_USER - 用户邮件 */
  MAIL_TYPE_USER = 2,
  UNRECOGNIZED = -1,
}

/** 邮件内容 */
export interface MailInfo {
  /** 邮件id */
  id: number;
  /** 邮件类型 */
  mailType: MailType;
  /** 邮件状态 */
  status: MailStatus;
  /** 邮件主题 */
  title: string;
  /** 邮件文本内容 */
  message: string;
  /** 发件人uid */
  sender: string;
  /** 收件人uid */
  receiver: string;
  /** 过期时间 */
  expire: number;
  /** 扩展信息，附件，发件人信息，收件人信息 */
  extra: string;
  /** 邮件发送时间 */
  timestamp: number;
}
