// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/player_data.proto

/* eslint-disable */


/** 玩家数据 */
export interface PlayerData {
  id: number;
  name: string;
  guildId: number;
}

export interface UserInfo {
  /** 唯一id */
  unionId: number;
  /** 账号 */
  account: string;
  /** 昵称 */
  nick: string;
  /** 邮箱 */
  email: string;
  /** 手机号码 */
  phoneNumber: string;
  /** 用户组 */
  group: number;
  /** 创建时间 */
  createTime: number;
}

export interface WorldUserInfo {
  uid: string;
  nick: string;
  gender: string;
  country: string;
  avatar: string;
  level: number;
  cups: number;
  gameId: number;
  gateId: number;
  gateAddress: string;
}

export interface EquipInfo {
  /** 装备模板id */
  id: number;
  /** 所装备的英雄 */
  hero: number;
  /** 随机属性 */
  attr: number[];
}

/** 英雄数据 */
export interface Hero {
  /** 英雄等级 */
  level: number;
  san: number;
  revocerTime: number;
  /** 当前所用的模型id */
  modelId: number;
  /** 皮肤id */
  skinId: number;
  /** 装备列表，记录装备实例id */
  equips: number[];
}

export interface BagItemNum {
  /** 总数量 */
  num: number;
  /** 可交易数量 */
  tradable: number;
}

/** 收藏品数据 */
export interface Collection {
  /** 等级 */
  level: number;
  /** 当前拥有数量 */
  num: number;
}

/** 背包数据 */
export interface BagInfo {
  /** 装备 */
  equips: { [key: number]: EquipInfo };
  /** 普通道具 */
  items: { [key: number]: BagItemNum };
  /** 卡牌 */
  cards: { [key: number]: BagItemNum };
  /** 漂流瓶 */
  driftBottles: { [key: number]: number };
  /** 拼图 */
  picturePuzzles: { [key: number]: number };
  /** 收藏品 */
  collections: { [key: number]: number };
  /** diy旗帜 */
  diyFlags: { [key: number]: number };
  /** 装备容量 */
  equipVolume: number;
  /** 已扩充次数 */
  extendNum: number;
}

export interface BagInfo_EquipsEntry {
  key: number;
  value: EquipInfo | undefined;
}

export interface BagInfo_ItemsEntry {
  key: number;
  value: BagItemNum | undefined;
}

export interface BagInfo_CardsEntry {
  key: number;
  value: BagItemNum | undefined;
}

export interface BagInfo_DriftBottlesEntry {
  key: number;
  value: number;
}

export interface BagInfo_PicturePuzzlesEntry {
  key: number;
  value: number;
}

export interface BagInfo_CollectionsEntry {
  key: number;
  value: number;
}

export interface BagInfo_DiyFlagsEntry {
  key: number;
  value: number;
}

/** 商店数据 */
export interface GoodsRecordInfo {
  /** 本期购买次数 */
  buyTimes: number;
  /** 总购买次数 */
  totalBuyTimes: number;
  /** 请求发起次数，包括未购买成功 */
  requestTimes: number;
  /** 最近一次刷新时间 */
  refreshTime: number;
  /** 奖励 todo */
  awards: string;
}

export interface ShopInfo {
  goods: { [key: number]: GoodsRecordInfo };
}

export interface ShopInfo_GoodsEntry {
  key: number;
  value: GoodsRecordInfo | undefined;
}

export interface TaskFreeAward {
  /** 免费奖励id */
  ids: number[];
  /** 上一次领取的奖励索引 */
  getIndex: number;
  /** 上一次领奖时间 */
  getTime: number;
}

export interface TaskInfo {
  /** 任务点 */
  awardPoint: number;
  /** 任务宝箱 */
  box: number;
  /** 免费奖励 */
  free:
    | TaskFreeAward
    | undefined;
  /** 今日任务刷新次数 */
  refreshNum: number;
  /** 任务宝箱生成序列 */
  boxSeq: number[];
  /** 任务宝箱版本号 */
  boxSeqVer: string;
  /** 免费奖励序列 */
  freeSeq: number[];
  /** 免费奖励版本号 */
  freeSeqVer: string;
  /** 任务列表 */
  taskList: { [key: number]: number };
}

export interface TaskInfo_TaskListEntry {
  key: number;
  value: number;
}

export interface WaitEventData {
  /** 事件id */
  id: number;
  /** 队伍id */
  team: number;
  /** 当时使用的工具 */
  tool: number;
}

export interface UserBaseInfo {
  /** 昵称 */
  nick: string;
  /** 性别 */
  gender: string;
  /** 国家 */
  country: string;
  /** 头像 */
  avatar: number;
  /** 设备号 */
  imel: string;
  /** 设备名 */
  device: string;
}

export interface LoginInfo {
  /** 首次登陆时间 */
  firstTime: number;
  /** 上次登录时间 */
  lastTime: number;
  /** 上次登录ip */
  lastIp: string;
  /** 累计登陆天数 */
  loginDays: number;
}

export interface PaymentInfo {
  /** 累计充值 */
  totalEcharge: number;
  /** 今日充值 */
  dailyRecharge: number;
  /** 最后一次充值金额 */
  lastRecharge: number;
  /** 最后一次充值时间 */
  lastRechargeTime: number;
}

export interface CosumeInfo {
  /** 历史消耗cash */
  cash: number;
  /** 历史消耗绑定cash */
  bindcash: number;
}

export interface ResourceInfo {
  /** 现有cash */
  cash: number;
  /** 现有绑定cash */
  bindcash: number;
  /** 经验 */
  exp: number;
  /** 金币 */
  gold: number;
  /** 书页 */
  fairyAge: number;
  /** 糖果 */
  candy: number;
}

export interface HeroTeam {
  heros: number[];
}

export interface BoxInfo {
  /** 宝箱实例id */
  bid: number;
  /** 宝箱id */
  id: number;
  /** 开启时间，已经解锁的才有时间 */
  time: number;
}

export interface DropInfo {
  num: number;
  cycle: number;
}

export interface ArenaInfo {
  /** 本次联赛历史最高奖杯 */
  historyCups: number;
  /** 领奖记录 */
  prizeRecord: number[];
  /** 胜利宝箱索引 */
  winBoxIndex: number;
  /** 总共胜利次数 */
  winCount: number;
  /** 当前连胜 */
  curWinRepeat: number;
  /** 最高连胜 */
  maxWinRepeat: number;
  /** 完胜次数，获得胜利时对方获得0皇冠的场次 */
  totalWin: number;
  /** 反败为胜次数 */
  turnTheTide: number;
  /** 本赛季参加次数 */
  seasonJoinCount: number;
  /** 本赛季胜利次数 */
  seasonWinCount: number;
  /** 上一届联赛id */
  preLeagueId: number;
  /** 本届联赛id */
  curLeagueId: number;
  preRankGlobal: number;
  preRankLocal: number;
  curRankGlobal: number;
  curRankLocal: number;
}

export interface MarkInfo {
  /** 角色名字修改次数 */
  userNameModifyCount: number;
  /** 公会名字修改次数 */
  guildNameModifyCount: number;
  /** 今日观看广告次数 */
  adTimesToday: number;
}

export interface BindInfo {
  wx: string;
  qq: string;
  fb: string;
  gmail: string;
  twitter: string;
}

export interface AdventureTeamInfo {
  /** 区域id */
  id: number;
  /** 开始探索时间 */
  startTime: number;
  /** 持续时间 */
  costTime: number;
  /** 移动开始时间 */
  moveStartTime: number;
  /** 移动起始坐标 */
  moveStartPoint: number;
  /** 移动目标 */
  moveTarget: number;
  /** 当前使用的探索工具 */
  usingTool: number;
  /** 英雄槽位 */
  slots: { [key: number]: number };
}

export interface AdventureTeamInfo_SlotsEntry {
  key: number;
  value: number;
}

export interface AdventureAreaInfo {
  level: number;
  progress: number;
  onceAward: { [key: number]: number };
  upgradeAward: { [key: number]: number };
}

export interface AdventureAreaInfo_OnceAwardEntry {
  key: number;
  value: number;
}

export interface AdventureAreaInfo_UpgradeAwardEntry {
  key: number;
  value: number;
}

export interface EventModInfo {
  seq: number[];
}

export interface RandomEventInfo {
  version: string;
  mod: EventModInfo | undefined;
}

export interface AdventureInfo {
  teams: AdventureTeamInfo | undefined;
  curSelectTeam: number;
  areas: { [key: number]: AdventureAreaInfo };
  randomEvent: RandomEventInfo | undefined;
}

export interface AdventureInfo_AreasEntry {
  key: number;
  value: AdventureAreaInfo | undefined;
}

export interface EventInfo {
  waitQueue: WaitEventData[];
  happend: { [key: number]: number };
}

export interface EventInfo_HappendEntry {
  key: number;
  value: number;
}

export interface ToolInfo {
  /** 工具id */
  id: number;
  /** 上次使用时间 */
  useTime: number;
  /** 本周期内使用次数 */
  useNum: number;
  /** 本周期内看广告次数 */
  adNum: number;
  /** 拥有的数量 */
  hasNum: number;
}

export interface CollectionInfo {
  id: number;
  level: number;
}

export interface WorkTableInfo {
  tools: { [key: number]: ToolInfo };
  collections: { [key: number]: CollectionInfo };
}

export interface WorkTableInfo_ToolsEntry {
  key: number;
  value: ToolInfo | undefined;
}

export interface WorkTableInfo_CollectionsEntry {
  key: number;
  value: CollectionInfo | undefined;
}

export interface FairyThemeInfo {
  /** 本次活动id */
  id: number;
  /** 当前活动等级 */
  level: number;
  /** 是否开启特别篇 */
  specialOpened: boolean;
  /** 领奖记录 */
  recordNormal: number;
  recordSpecial: number;
}

export interface GuideInfo {
  /** 当前引导任务id */
  taskId: number;
  /** 当前步骤id */
  stepId: number;
  /** 跳过的步骤 */
  jumpRecord: { [key: number]: number };
  /** 已完成的任务id */
  finishedTaskIds: number[];
}

export interface GuideInfo_JumpRecordEntry {
  key: number;
  value: number;
}

/** 公会信息 */
export interface UserGuildInfo {
  gid: string;
  name: string;
  flag: number;
  location: string;
}

export interface UserProfile {
  uid: string;
  openId: string;
  /** 基础信息 */
  info:
    | UserBaseInfo
    | undefined;
  /** 登录信息 */
  login:
    | LoginInfo
    | undefined;
  /** 等级 */
  level: number;
  /** 杯数 */
  cups: number;
  /** 历史最高杯数 */
  historyMaxCups: number;
  /** 观看广告次数 */
  adTimes: number;
  /** 是否是游客账号 */
  guest: number;
  /** 充值信息 */
  payment:
    | PaymentInfo
    | undefined;
  /** 消费信息 */
  consume:
    | CosumeInfo
    | undefined;
  /** 玩家可以获得和消耗的一些资源 */
  resource:
    | ResourceInfo
    | undefined;
  /** 英雄列表 */
  heros: { [key: number]: Hero };
  /** 上阵英雄小队 */
  heroTeams: { [key: number]: HeroTeam };
  /** 当前使用的英雄队伍 */
  curHeroTeam: number;
  /** 背包数据 */
  bag:
    | BagInfo
    | undefined;
  /** 商店数据 */
  shop:
    | ShopInfo
    | undefined;
  /** 邮件信息 */
  mail: { [key: string]: number };
  /** 任务信息 */
  task:
    | TaskInfo
    | undefined;
  /** 宝箱数据 */
  box: { [key: number]: BoxInfo };
  /** 掉落数据 */
  drop: { [key: number]: DropInfo };
  /** 竞技场数据 */
  arena: ArenaInfo | undefined;
  mark:
    | MarkInfo
    | undefined;
  /** 绑定的第三方账号信息信息 */
  bind:
    | BindInfo
    | undefined;
  /** 已经获得的头像 */
  hasAvatars: number[];
  /** 冒险数据 */
  adventure: AdventureInfo | undefined;
  events:
    | EventInfo
    | undefined;
  /** 工作台数据 */
  workTable:
    | WorkTableInfo
    | undefined;
  /** 书页数据 */
  fairyTheme:
    | FairyThemeInfo
    | undefined;
  /** 引导数据 */
  guide:
    | GuideInfo
    | undefined;
  /** 已解锁的皮肤 */
  unlockedSkins: number[];
  /** 记录皮肤的过期时间 */
  skinExpire: { [key: number]: number };
  markedSaleIds: number[];
  markedGoods: string[];
  diyFlags: { [key: number]: number };
  /** 客户端自定义数据 */
  customData: string;
  /** 公会数据 */
  guild: UserGuildInfo | undefined;
}

export interface UserProfile_HerosEntry {
  key: number;
  value: Hero | undefined;
}

export interface UserProfile_HeroTeamsEntry {
  key: number;
  value: HeroTeam | undefined;
}

export interface UserProfile_MailEntry {
  key: string;
  value: number;
}

export interface UserProfile_BoxEntry {
  key: number;
  value: BoxInfo | undefined;
}

export interface UserProfile_DropEntry {
  key: number;
  value: DropInfo | undefined;
}

export interface UserProfile_SkinExpireEntry {
  key: number;
  value: number;
}

export interface UserProfile_DiyFlagsEntry {
  key: number;
  value: number;
}
