// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/rank_data.proto

/* eslint-disable */


/** 排行榜类型 */
export enum RankType {
  RANK_TYPE_UNKNOWN = 0,
  /** GLOBAL_LEAGUE_CUR_CUPS - 本届联赛杯数全球榜 */
  GLOBAL_LEAGUE_CUR_CUPS = 1001,
  /** GLOBAL_LEAGUE_LAST_CUPS - 上届联赛杯数全球榜 */
  GLOBAL_LEAGUE_LAST_CUPS = 1002,
  /** GLOBAL_GUILD_CUPS - 公会杯数全球榜 */
  GLOBAL_GUILD_CUPS = 1003,
  /** LOCAL_LEAGUE_CUR_CUPS - 本届联赛杯数地区榜 */
  LOCAL_LEAGUE_CUR_CUPS = 2001,
  /** LOCAL_LEAGUE_LAST_CUPS - 上届联赛杯数地区榜 */
  LOCAL_LEAGUE_LAST_CUPS = 2002,
  /** LOCAL_GUILD_CUPS - 公会杯数地区榜 */
  LOCAL_GUILD_CUPS = 2003,
  UNRECOGNIZED = -1,
}

export interface RankNodeInfo {
  nodeId: string;
  score: number;
  rank: number;
  extra: string;
  updatedAt: number;
}
