// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/trading_data.proto

/* eslint-disable */


/** 出售物品状态 */
export enum SaleItemStatus {
  SALE_ITEM_STATE_UNKNOWN = 0,
  /** SALE_ITEM_STATE_PUBLICITY - 公示期 */
  SALE_ITEM_STATE_PUBLICITY = 1,
  /** SALE_ITEM_STATE_TRADING - 交易期 */
  SALE_ITEM_STATE_TRADING = 2,
  /** SALE_ITEM_STATE_VERIFY - 审核期 */
  SALE_ITEM_STATE_VERIFY = 3,
  /** SALE_ITEM_STATE_CLAIM - 可领取 */
  SALE_ITEM_STATE_CLAIM = 4,
  /** SALE_ITEM_STATE_EXPIRE - 超时 */
  SALE_ITEM_STATE_EXPIRE = 5,
  UNRECOGNIZED = -1,
}

/** 记录类型，出售还是购买 */
export enum SaleRecordType {
  /** SALE_RECORD_TYPE_SALE - 出售 */
  SALE_RECORD_TYPE_SALE = 0,
  /** SALE_RECORD_TYPE_BUY - 购买 */
  SALE_RECORD_TYPE_BUY = 1,
  UNRECOGNIZED = -1,
}

export interface StorageItemInfo {
  /** 商品唯一id */
  itemUuid: number;
  /** 商品id */
  itemId: number;
  /** 商品类型 */
  itemType: string;
  /** 商品标签 */
  itemTag: string;
  /** 商品数量 */
  itemCount: number;
}

export interface SaleItemInfo {
  /** 商品唯一id */
  saleId: number;
  /** 商品id */
  itemId: number;
  /** 商品类型 */
  itemType: string;
  /** 商品标签 */
  itemTag: string;
  /** 商品数量 */
  itemCount: number;
  /** 商品状态 */
  status: number;
  /** 上架时间 */
  createAt: number;
  /** 价格 */
  price: number;
  /** 收藏数 */
  markCount: number;
  /** 卖家id */
  sellerId: string;
  /** 公示时间 */
  publicityTime: number;
}

export interface SaleRecordInfo {
  /** 记录类型 */
  recordType: SaleRecordType;
  /** 交易的物品id */
  itemId: number;
  /** 交易数量 */
  itemCount: number;
  /** 价格 */
  itemPrice: number;
  /** 时间戳 */
  timestamp: number;
  itemType: string;
}

/** 钱包数据 */
export interface WalletInfo {
  /** 余额 */
  balance: number;
}

export interface GoodsInfo {
  itemType: string;
  itemId: number;
  itemCount: number;
  markCount: number;
}
