// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: chat/chat.proto

/* eslint-disable */
import type { ChatMessageInfo, ChatTipsInfo, GetChatTipsParam } from "../common/chat_data";


/** 发送消息 */
export interface CSendMessage {
  channelId: string;
  message: string;
}

export interface SSendMessage {
  /** 新增的消息列表 */
  addedMessages: ChatMessageInfo[];
}

/** 获取聊天记录 */
export interface CGetChatLog {
  channelId: string;
  minMessageId: number;
  maxMessageId: number;
  lastLoadTimestamp: number;
  loadType: number;
}

export interface SGetChatLog {
  /** 消息列表 */
  messages: ChatMessageInfo[];
}

export interface CGetChatTips {
  params: GetChatTipsParam[];
}

export interface SGetChatTips {
  tips: ChatTipsInfo[];
}
