// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: common/guild_data.proto

/* eslint-disable */


export interface GuildData {
  id: number;
  name: string;
}
