// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/adventure.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";
import type { AdventureTeamInfo } from "../common/player_data";


/** 开始探索 */
export interface CStartExplore {
}

export interface SStartExplore {
  startTime: number;
  costTime: number;
  teams: AdventureTeamInfo[];
}

/** 停止探索 */
export interface CStopExplore {
}

export interface SStopExplore {
  startTime: number;
}

/** 前往区域 */
export interface CGotoArea {
  id: number;
}

export interface SGotoArea {
  moveStartPoint: number;
  target: number;
  moveStartTime: number;
}

/** 触发事件 */
export interface CTriggerEvent {
}

export interface STriggerEvent {
  eventCount: number;
  id: number;
}

/** 派遣英雄 */
export interface CSendHero {
  cardId: number;
  index: number;
}

export interface SSendHero {
  slots: number[];
}

/** 设置工具 */
export interface CSetTools {
  id: number;
}

export interface SSetTools {
}

/** 领取一次性奖励 */
export interface CClaimOnceAward {
  index: number;
}

export interface SClaimOnceAward {
  awards: Reward[];
}

/** 切换探险队伍 */
export interface CSwitchTeam {
  teamId: number;
}

export interface SSwitchTeam {
}

/** 购买探险工具 */
export interface CBuyTools {
  id: number;
}

export interface SBuyTools {
  costs: Reward[];
}

/** 区域升级 */
export interface CUpgradeArea {
  areaId: number;
}

export interface SUpgradeArea {
  costs: Reward[];
  awards: Reward[];
  level: number;
}

/** 领取区域升级奖励 */
export interface CClaimAreaUpgradeAward {
  areaId: number;
  level: number;
}

export interface SClaimAreaUpgradeAward {
  awards: Reward[];
}
