// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/bag.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";


/** 使用道具 */
export interface CUseBagItem {
  id: number;
  num: number;
}

export interface SUseBagItem {
  awards: Reward[];
  costs: Reward[];
}

/** 出售背包道具 */
export interface CSellBagItem {
  id: number;
  num: number;
}

export interface SSellBagItem {
  awards: Reward[];
  costs: Reward[];
}

/** 扩展装备背包格子 */
export interface CExtendEquipBag {
}

export interface SExtendEquipBag {
  costs: Reward[];
}

/** 分解装备 */
export interface CDecomposeEquip {
  eids: number[];
  quality: number;
}

export interface SDecomposeEquip {
  awards: Reward[];
  costs: Reward[];
}
