// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/debug.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";


export interface CEcho {
  text: string;
}

export interface SEcho {
  text: string;
}

/** 添加装备 */
export interface CDebugAddEquip {
  id: number;
  num: number;
}

export interface SDebugAddEquip {
  awards: Reward[];
}

/** 添加道具 */
export interface CDebugAddItem {
  id: number;
  num: number;
}

export interface SDebugAddItem {
  awards: Reward[];
}

/** 添加卡牌 */
export interface CDebugAddCard {
  id: number;
  num: number;
  /** 是否可交易 */
  tradable: boolean;
}

export interface SDebugAddCard {
  awards: Reward[];
}

/** 修改杯数 */
export interface CDebugAddCups {
  cups: number;
}

export interface SDebugAddCups {
}

/** 增加经验 */
export interface CDebugAddExp {
  exp: number;
}

export interface SDebugAddExp {
}

/** 增加钻石 */
export interface CDebugAddCash {
  val: number;
}

export interface SDebugAddCash {
}

/** 添加宝箱 */
export interface CDebugAddBox {
  boxId: number;
  num: number;
}

export interface SDebugAddBox {
  awards: Reward[];
}

/** 添加书页 */
export interface CDebugAddPages {
  pages: number;
}

export interface SDebugAddPages {
}

/** 添加糖果 */
export interface CDebugAddCandy {
  val: number;
}

export interface SDebugAddCandy {
}

/** 触发冒险事件 */
export interface CDebugTriggerEvent {
  /** 事件id */
  id: number;
  tool: number;
  teamId: number;
}

export interface SDebugTriggerEvent {
}

/** 修改交易余额 */
export interface CDebugSetTradingBalance {
}

export interface SDebugSetTradingBalance {
}

/** 添加漂流瓶 */
export interface CDebugAddDriftBottle {
  id: number;
  num: number;
}

export interface SDebugAddDriftBottle {
  awards: Reward[];
}

/** 添加拼图 */
export interface CDebugAddPuzzlePiece {
  id: number;
  num: number;
}

export interface SDebugAddPuzzlePiece {
  awards: Reward[];
}

/** 添加收藏品 */
export interface CDebugAddCollection {
  id: number;
  num: number;
}

export interface SDebugAddCollection {
  awards: Reward[];
}

/** 增加冒险进度 */
export interface CDebugAddAdventureProgress {
  val: number;
}

export interface SDebugAddAdventureProgress {
}
