// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/fairy_theme.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";


/** 领取奖励 */
export interface CClaimFairyThemeReward {
  level: number;
  special: boolean;
}

export interface SClaimFairyThemeReward {
  awards: Reward[];
}

/** 开启特殊篇幅 */
export interface COpenSpecialFairyTheme {
}

export interface SOpenSpecialFairyTheme {
  costs: Reward[];
}

/** 购买书页 */
export interface CBuyPages {
}

export interface SBuyPages {
  costs: Reward[];
  awards: Reward[];
  level: number;
}
