// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/friend.proto

/* eslint-disable */
import type { ApplyInfo, FriendUserInfo } from "../common/friend_data";


/** 获取好友列表 */
export interface CGetFriendList {
}

export interface SGetFriendList {
  list: FriendUserInfo[];
}

/** 获取好友申请列表 */
export interface CGetApplyList {
}

export interface SGetApplyList {
  list: ApplyInfo[];
}

/** 添加好友 */
export interface CAddFriend {
  target: string;
  /** 申请者的信息 */
  user:
    | FriendUserInfo
    | undefined;
  /** 扩展信息 */
  extra: string;
}

export interface SAddFriend {
}

/** 移除好友 */
export interface CRemoveFriend {
  target: string;
}

export interface SRemoveFriend {
}

/** 添加好友回复 */
export interface CReplyAdd {
  target: string;
  /** 1 同意， 2 拒绝 */
  result: number;
  user: FriendUserInfo | undefined;
}

export interface SReplyAdd {
}
