// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/guild.proto

/* eslint-disable */
import type { GuildApplyInfo, GuildInfo, GuildSimpleInfo } from "../common/guild_data";


/** 获取公会信息 */
export interface CGetGuild {
  uid: string;
  gid: string;
}

export interface SGetGuild {
  info: GuildInfo | undefined;
}

/** 获取公会列表 */
export interface CGetGuildList {
  offset: number;
  limit: number;
}

export interface SGetGuildList {
  list: GuildSimpleInfo[];
}

/** 创建公会 */
export interface CCreateGuild {
  name: string;
  flag: number;
  location: string;
  joinType: number;
  joinLimit: number;
}

export interface SCreateGuild {
  info: GuildInfo | undefined;
}

/** 离开公会 */
export interface CLeaveGuild {
}

export interface SLeaveGuild {
  gid: string;
}

/** 申请加入 */
export interface CApplyJoin {
  gid: string;
  apply: GuildApplyInfo | undefined;
}

export interface SApplyJoin {
}

/** 获取申请列表 */
export interface CGetGuildApplyList {
}

export interface SGetGuildApplyList {
  list: GuildApplyInfo[];
}

/** 回复申请 */
export interface CReplyJoin {
  targetUid: string;
  agree: boolean;
}

export interface SReplyJoin {
}

/** 踢出成员 */
export interface CKickMember {
  targetUid: string;
}

export interface SKickMember {
}

/** 修改公会名称 */
export interface CModifyGuildName {
  name: string;
}

export interface SModifyGuildName {
}

/** 修改公告 */
export interface CModifyNotice {
  notice: string;
}

export interface SModifyNotice {
}

/** 修改旗帜 */
export interface CModifyFlag {
  flag: number;
}

export interface SModifyFlag {
}

/** 修改公会信息 */
export interface CModifyGuild {
  name: string;
  flag: number;
  location: string;
  joinType: number;
  joinLimit: number;
}

export interface SModifyGuild {
}

/** 设置成员职位 */
export interface CSetMemberType {
  targetUid: string;
  type: string;
}

export interface SSetMemberType {
}

/** 转移会长 */
export interface CTransferLeader {
  targetUid: string;
}

export interface STransferLeader {
}
