// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/league.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";


/** 领取联赛奖励 */
export interface CClaimLeagueReward {
  level: number;
  id: number;
  index: number;
}

export interface SClaimLeagueReward {
  awards: Reward[];
}
