// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/player.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";
import type { HeroTeam, UserProfile } from "../common/player_data";


/** 心跳 */
export interface CHeartBeat {
}

export interface SHeartBeat {
  timestamp: number;
}

/** 登录game，返回完整的用户数据 */
export interface CLoginGame {
}

export interface SLoginGame {
  userProfile: UserProfile | undefined;
}

/** 登出 */
export interface CLogoutGame {
}

export interface SLogoutGame {
}

/** 查看玩家信息 */
export interface CViewUserInfo {
}

export interface SViewUserInfo {
}

/** 修改玩家名字 */
export interface CModifyName {
  newName: string;
}

export interface SModifyName {
}

/** 修改头像 */
export interface CModifyAvatar {
  avatar: number;
}

export interface SModifyAvatar {
}

/** 绑定账号 */
export interface CBindAccount {
  bindType: number;
  bindAccount: string;
  bindOpenid: string;
}

export interface SBindAccount {
}

/** 设置上阵英雄 */
export interface CSetFightHero {
  teamId: number;
  slotId: number;
  cardId: number;
}

export interface SSetFightHero {
  /** 旧的卡牌id */
  old: number;
}

/** 下阵英雄 */
export interface CUnsetFightHero {
  teamId: number;
  slotId: number;
}

export interface SUnsetFightHero {
  old: number;
}

/** 英雄升级 */
export interface CUpgradeHero {
  cardId: number;
}

export interface SUpgradeHero {
  /** 新的等级 */
  newLevel: number;
  /** 消耗 */
  costs: Reward[];
  /** 获得 */
  awards: Reward[];
}

/** 英雄换肤 */
export interface CChangeHeroSkin {
  /** 英雄id */
  heroId: number;
  /** 皮肤id */
  skinId: number;
}

export interface SChangeHeroSkin {
}

/** 切换当前使用的队伍 */
export interface CSwitchHeroTeam {
  teamId: number;
}

export interface SSwitchHeroTeam {
  curHeroTeam: number;
  heroTeams: { [key: number]: HeroTeam };
}

export interface SSwitchHeroTeam_HeroTeamsEntry {
  key: number;
  value: HeroTeam | undefined;
}

/** 更新引导 */
export interface CUpdateGuide {
  valMap: { [key: string]: string };
}

export interface CUpdateGuide_ValMapEntry {
  key: string;
  value: string;
}

export interface SUpdateGuide {
}

export interface CEquipDiyFlag {
  id: number;
  cancel: boolean;
}

export interface SEquipDiyFlag {
}

export interface CSetUserData {
  customData: string;
}

export interface SSetUserData {
}
