// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/replay.proto

/* eslint-disable */
import type { ReplayData } from "../common/battle_data";


/** 获取最近一次胜利的战报 */
export interface CGetLastWinData {
}

export interface SGetLastWinData {
}

/** 获取战报列表 */
export interface CGetReplayList {
}

export interface SGetReplayList {
}

/** 获取指定战报 */
export interface CGetReplay {
  /** 战报id */
  key: string;
}

export interface SGetReplay {
  replay: ReplayData | undefined;
}
