// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/task.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";


/** 开启任务宝箱 */
export interface COpenTaskBox {
  /** 是否看广告打开 */
  isPayOpen: boolean;
}

export interface SOpenTaskBox {
  awards: Reward[];
  /** 返回新的宝箱id */
  newBox: number;
  awardPoint: number;
}

/** 领取免费奖励 */
export interface CClaimTaskFreeAward {
  isDouble: boolean;
}

export interface SClaimTaskFreeAward {
  awards: Reward[];
  awardPoint: number;
  getTime: number;
  getIndex: number;
}

/** 完成任务 */
export interface CFinishTask {
  id: number;
}

export interface SFinishTask {
  awards: Reward[];
  awardPoint: number;
}

/** 刷新普通任务 */
export interface CRefreshTask {
  id: number;
}

export interface SRefreshTask {
  costs: Reward[];
  newTaskId: number;
}
