// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/trading.proto

/* eslint-disable */
import type { GoodsInfo, SaleItemInfo, SaleRecordInfo, StorageItemInfo, WalletInfo } from "../common/trading_data";


/** 上架商品 */
export interface CPutOnSale {
  /** 商品id */
  itemId: number;
  /** 商品类型 */
  itemType: string;
  /** 商品标签 */
  itemTag: string;
  /** 商品数量 */
  itemCount: number;
  /** 价格 */
  itemPrice: number;
  /** 公示时间 */
  publicityTime: number;
}

export interface SPutOnSale {
  saleInfo: SaleItemInfo | undefined;
}

/** 下架商品 */
export interface CTakeSaleOff {
  /** 商品唯一id */
  itemUuid: number;
}

export interface STakeSaleOff {
  /** 下架后先到仓库 */
  storageItem: StorageItemInfo | undefined;
}

/** 获取自己的仓库信息 */
export interface CGetMyStorage {
}

export interface SGetMyStorage {
  /** 商品列表 */
  itemList: StorageItemInfo[];
  /** 钱包数据 */
  walletInfo: WalletInfo | undefined;
}

/** 查询可购买的物品 */
export interface CQuerySales {
  /** 商品类型 */
  itemType: string;
  /** 商品id */
  itemId: number;
  /** 开始位置 */
  offset: number;
  /** 数量 */
  limit: number;
}

export interface SQuerySales {
  sales: SaleItemInfo[];
}

export interface CQueryGoods {
  /** 商品类型 */
  itemType: string;
  /** 开始位置 */
  offset: number;
  /** 数量 */
  limit: number;
}

export interface SQueryGoods {
  goodsList: GoodsInfo[];
}

/** 获取自身已上架商品 */
export interface CGetMySales {
}

export interface SGetMySales {
  sales: SaleItemInfo[];
}

/** 购买商品 */
export interface CPurchaseItem {
  /** 商品id */
  saleId: number;
  /** 购买数量 */
  count: number;
}

export interface SPurchaseItem {
  /** 购买成功的商品 */
  storageItem: StorageItemInfo | undefined;
}

/** 获取交易记录 */
export interface CGetRecords {
}

export interface SGetRecords {
  records: SaleRecordInfo[];
}

/** 收藏商品 */
export interface CMarkSale {
  /** 商品id */
  saleId: number;
  /** 是否取消收藏 */
  cancel: boolean;
}

export interface SMarkSale {
  saleId: number;
}

/** 获取我的收藏 */
export interface CGetMyMarkedSales {
}

export interface SGetMyMarkedSales {
  sales: SaleItemInfo[];
}

export interface CMarkGoods {
  /** 商品类型 */
  itemType: string;
  /** 商品id */
  itemId: number;
  /** 是否取消收藏 */
  cancel: boolean;
}

export interface SMarkGoods {
  goodsKey: string;
}

/** 获取我的收藏 */
export interface CGetMyMarkedGoods {
  goodsKey: string[];
}

export interface SGetMyMarkedGoods {
  goodsList: GoodsInfo[];
}

/** 获取商品推荐价格 */
export interface CGetRecommendPrice {
  itemId: number;
}

export interface SGetRecommendPrice {
  price: number;
}
