// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: game/treasure.proto

/* eslint-disable */
import type { Reward } from "../common/item_data";


/** 解锁宝箱 */
export interface CUnlockTreatureBox {
  bid: number;
  useCash: boolean;
}

export interface SUnlockTreatureBox {
  /** 开始时间 */
  time: number;
  awards: Reward[];
  costs: Reward[];
}

/** 开启宝箱 */
export interface COpenTreatureBox {
  bid: number;
  useCash: boolean;
}

export interface SOpenTreatureBox {
  awards: Reward[];
  costs: Reward[];
}

/** 宝箱加速 */
export interface CSpeedUpTreatureBox {
  /** 宝箱实例id */
  bid: number;
}

export interface SSpeedUpTreatureBox {
  boxId: number;
  time: number;
}
