// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.0
// source: mail/mail.proto

/* eslint-disable */
import type { MailInfo, MailType } from "../common/mail_data";


/** 获取邮件列表 */
export interface CGetMailList {
  /** 已经领取的系统邮件id，用来过滤系统邮件的 */
  mailIds: number[];
}

export interface SGetMailList {
  list: MailInfo[];
}

/** 读取邮件 */
export interface CReadMail {
  /** 邮件id */
  mailId: number;
  /** 邮件类型 */
  mailType: MailType;
}

export interface SReadMail {
}

/** 删除邮件 */
export interface CDeleteMail {
  /** 邮件id */
  mailIds: number[];
}

export interface SDeleteMail {
  /** 删除成功的邮件id */
  mailIds: number[];
}

/** 领取邮件 */
export interface CClaimMail {
  /** 邮件id */
  mailId: number;
  /** 邮件类型 */
  mailType: MailType;
}

export interface SClaimMail {
  /** 附件 */
  extra: string;
}

/** 一键领取 */
export interface CClaimAllMail {
}

export interface SClaimAllMail {
  /** 附件 */
  extra: string[];
}
